package docs

import (
	"encoding/json"
	"os"
	"reflect"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

// definicionesSSE son los esquemas del canal de eventos que T03 fija en el
// namespace http.*. Se comparan en los tres artefactos generados a la vez:
// si falta en alguno, la documentación de Swagger no es desplegable.
var definicionesSSE = []string{
	"http.SSEEventPayload",
	"http.SSEDetallesEvento",
	"http.TaskSuccess",
	"http.TaskFailed",
	"http.SSETicketResponse",
	"http.SSECierrePayload",
	"http.SSETiposPayload",
}

// TestContratoEtapa1ArtefactosJSONYAML exige que swagger.yaml diga lo mismo que
// swagger.json. Sin esto, Swagger UI sirve el JSON pero cualquier consumo del
// YAML documentaría otro contrato.
func TestContratoEtapa1ArtefactosJSONYAML(t *testing.T) {
	desdeJSON := leerSwaggerJSON(t)
	desdeYAML := leerSwaggerYAML(t)

	if v := desdeYAML["swagger"]; v != "2.0" {
		t.Errorf("swagger.yaml declara swagger=%v, se esperaba \"2.0\"", v)
	}
	if v := desdeJSON["swagger"]; v != desdeYAML["swagger"] {
		t.Errorf("swagger=%v en JSON y %v en YAML", desdeJSON["swagger"], desdeYAML["swagger"])
	}
	if v := desdeJSON["basePath"]; v != desdeYAML["basePath"] {
		t.Errorf("basePath %v en JSON y %v en YAML", desdeJSON["basePath"], desdeYAML["basePath"])
	}

	compararSecciones(t, desdeJSON, desdeYAML, "paths")
	compararSecciones(t, desdeJSON, desdeYAML, "definitions")
	compararSecciones(t, desdeJSON, desdeYAML, "securityDefinitions")

	// Los esquemas SSE tienen que estar en los dos formatos, no solo en el JSON.
	definicionesYAML := objeto(t, desdeYAML, "definitions")
	for _, nombre := range definicionesSSE {
		if _, ok := definicionesYAML[nombre]; !ok {
			t.Errorf("swagger.yaml no define %s", nombre)
		}
	}
}

// TestContratoEtapa1ArtefactosJSONGo exige que el docTemplate de docs.go
// contenga el mismo contrato que swagger.json. docs.go es lo que realmente
// registra swaggo y sirve la UI, así que un swagger.json desactualizado
// documentaría una API que el servidor no expone.
func TestContratoEtapa1ArtefactosJSONGo(t *testing.T) {
	desdeJSON := leerSwaggerJSON(t)
	desdeGo := leerSpecDeDocsGo(t)

	compararSecciones(t, desdeJSON, desdeGo, "paths")
	compararSecciones(t, desdeJSON, desdeGo, "definitions")
	compararSecciones(t, desdeJSON, desdeGo, "securityDefinitions")

	definicionesGo := objeto(t, desdeGo, "definitions")
	for _, nombre := range definicionesSSE {
		if _, ok := definicionesGo[nombre]; !ok {
			t.Errorf("docs.go no define %s", nombre)
		}
	}
	if _, existe := definicionesGo["ports.RealtimeEvent"]; existe {
		t.Error("docs.go no debe definir ports.RealtimeEvent: el contrato SSE vive en http.*")
	}
}

// TestContratoEtapa1ArtefactosMismaCorrida exige que los tres artefactos
// provengan de la misma corrida de swag. Swag escribe los archivos de a uno, así
// que una generación interrumpida deja swagger.json describiendo una API que
// docs.go no registra. Se compares el título y la versión declarados en docs.go
// contra los que quedaron embebidos en los otros dos formatos.
func TestContratoEtapa1ArtefactosMismaCorrida(t *testing.T) {
	contenidoDocsGo := leerArchivo(t, "docs.go")
	for _, marcador := range []string{
		"// Package docs Code generated by swaggo/swag. DO NOT EDIT",
		"LeftDelim:",
	} {
		if !strings.Contains(contenidoDocsGo, marcador) {
			t.Errorf("docs.go perdió el marcador %q: el archivo fue editado a mano o quedó truncado", marcador)
		}
	}

	infoGo := map[string]string{
		"title":    valorConstante(t, contenidoDocsGo, "Title:"),
		"version":  valorConstante(t, contenidoDocsGo, "Version:"),
		"basePath": valorConstante(t, contenidoDocsGo, "BasePath:"),
	}

	fromJSON := objeto(t, leerSwaggerJSON(t), "info")
	if fromJSON["title"] != infoGo["title"] {
		t.Errorf("swagger.json title=%v y docs.go Title=%s", fromJSON["title"], infoGo["title"])
	}
	if fromJSON["version"] != infoGo["version"] {
		t.Errorf("swagger.json version=%v y docs.go Version=%s", fromJSON["version"], infoGo["version"])
	}
	if basePath := leerSwaggerJSON(t)["basePath"]; basePath != infoGo["basePath"] {
		t.Errorf("swagger.json basePath=%v y docs.go BasePath=%s", basePath, infoGo["basePath"])
	}

	fromYAML := objeto(t, leerSwaggerYAML(t), "info")
	if fromYAML["title"] != infoGo["title"] {
		t.Errorf("swagger.yaml title=%v y docs.go Title=%s", fromYAML["title"], infoGo["title"])
	}
	if fromYAML["version"] != infoGo["version"] {
		t.Errorf("swagger.yaml version=%v y docs.go Version=%s", fromYAML["version"], infoGo["version"])
	}
}

// valorConstante extrae el literal de cadena que sigue a una clave dentro del
// bloque SwaggerInfo de docs.go.
func valorConstante(t *testing.T, contenido, clave string) string {
	t.Helper()
	desde := strings.Index(contenido, clave)
	if desde < 0 {
		t.Fatalf("docs.go no declara %s", clave)
	}
	resto := contenido[desde+len(clave):]
	apertura := strings.Index(resto, `"`)
	if apertura < 0 {
		t.Fatalf("%s no es una cadena en docs.go", clave)
	}
	cierre := strings.Index(resto[apertura+1:], `"`)
	if cierre < 0 {
		t.Fatalf("%s no cierra la cadena en docs.go", clave)
	}
	return resto[apertura+1 : apertura+1+cierre]
}

// compararSecciones exige que dos documentos tengan la misma sección, clave por
// clave, con el mismo valor.
func compararSecciones(t *testing.T, esperado, obtenido map[string]any, seccion string) {
	t.Helper()
	izquierda, ok := esperado[seccion]
	if !ok {
		t.Fatalf("el documento de referencia no tiene la sección %q", seccion)
	}
	derecha, existe := obtenido[seccion]
	if !existe {
		t.Fatalf("el documento comparado no tiene la sección %q", seccion)
	}
	if !reflect.DeepEqual(izquierda, derecha) {
		t.Errorf("la sección %q no coincide entre los artefactos: %s", seccion, primerDesvio(izquierda, derecha, seccion))
	}
}

// primerDesvio describe la primera diferencia entre dos secciones para que el
// fallo sea accionable sin volcar el contrato entero.
func primerDesvio(esperado, obtenido any, ruta string) string {
	esperadoObj, ok := esperado.(map[string]any)
	if !ok {
		return "en " + ruta
	}
	obtenidoObj, ok := obtenido.(map[string]any)
	if !ok {
		return ruta + " no es un objeto"
	}
	for clave, valor := range esperadoObj {
		otro, existe := obtenidoObj[clave]
		if !existe {
			return ruta + "." + clave + " falta"
		}
		if !reflect.DeepEqual(valor, otro) {
			return primerDesvio(valor, otro, ruta+"."+clave)
		}
	}
	for clave := range obtenidoObj {
		if _, existe := esperadoObj[clave]; !existe {
			return ruta + "." + clave + " sobra"
		}
	}
	return ruta + " difiere"
}

func leerSwaggerJSON(t *testing.T) map[string]any {
	t.Helper()
	var documento map[string]any
	if err := json.Unmarshal([]byte(leerArchivo(t, "swagger.json")), &documento); err != nil {
		t.Fatalf("decodificar swagger.json: %v", err)
	}
	return documento
}

// leerSwaggerYAML normaliza el YAML a JSON para poder compararlo con swagger.json
// sin caring por cómo representa cada formato los mismos números.
func leerSwaggerYAML(t *testing.T) map[string]any {
	t.Helper()
	var crudo any
	if err := yaml.Unmarshal([]byte(leerArchivo(t, "swagger.yaml")), &crudo); err != nil {
		t.Fatalf("decodificar swagger.yaml: %v", err)
	}
	normalizado, err := json.Marshal(crudo)
	if err != nil {
		t.Fatalf("normalizar swagger.yaml a JSON: %v", err)
	}
	var documento map[string]any
	if err := json.Unmarshal(normalizado, &documento); err != nil {
		t.Fatalf("decodificar swagger.yaml normalizado: %v", err)
	}
	return documento
}

// leerSpecDeDocsGo extrae el docTemplate de docs.go. Swag lo escribe como un
// literal crudo con las acciones de Go concatenadas para los backticks, así que
// se deshacen antes de sustituir los marcadores que rellena swaggo en runtime.
func leerSpecDeDocsGo(t *testing.T) map[string]any {
	t.Helper()
	contenido := leerArchivo(t, "docs.go")

	const inicio = "const docTemplate = `"
	desde := strings.Index(contenido, inicio)
	if desde < 0 {
		t.Fatal("docs.go no declara docTemplate")
	}
	desde += len(inicio)
	hasta := strings.Index(contenido[desde:], "`\n")
	if hasta < 0 {
		hasta = strings.Index(contenido[desde:], "`\r\n")
	}
	if hasta < 0 {
		t.Fatal("docs.go no cierra docTemplate")
	}
	plantilla := contenido[desde : desde+hasta]

	// "`" + "`" + `" es un backtick escapado en el literal crudo de Go.
	plantilla = strings.ReplaceAll(plantilla, "` + \"`\" + `", "`")

	// Swaggo reemplaza estos marcadores cuando sirve la UI. Se sustituyen por
	// valores válidos para poder decodificar el resto como JSON.
	for marcador, valor := range map[string]string{
		"{{ marshal .Schemes }}":   "[]",
		"{{escape .Description}}":  "",
		"{{.Title}}":               "El Centinela API",
		"{{.Version}}":             "1.0",
		"{{.Host}}":                "",
		"{{.BasePath}}":            "/api",
		"{{.LeftDelim}}":           "{{",
		"{{.RightDelim}}":          "}}",
		"{{.InstanceName}}":        "swagger",
		"{{.SwaggerTemplate}}":     "",
		"{{ marshal .Info }}":      "{}",
		"{{.MarkdownDescription}}": "",
	} {
		plantilla = strings.ReplaceAll(plantilla, marcador, valor)
	}

	var documento map[string]any
	if err := json.Unmarshal([]byte(plantilla), &documento); err != nil {
		t.Fatalf("decodificar el docTemplate de docs.go: %v", err)
	}
	return documento
}

func leerArchivo(t *testing.T, nombre string) string {
	t.Helper()
	contenido, err := os.ReadFile(nombre)
	if err != nil {
		t.Fatalf("leer %s: %v", nombre, err)
	}
	return string(contenido)
}
